name: social_app
description: "A multi-platform social media app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  iconsax: 0.0.8
  
  #Cupertino Icons
  cupertino_icons: ^1.0.8

  #local storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.1.0
  rx_shared_preferences: ^3.1.0

  #state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5

  #talker & logger
  talker_flutter: ^4.1.3
  talker_bloc_logger: ^4.1.3
  talker_dio_logger: ^4.6.11

  dartz: ^0.10.1
  dartx: ^1.2.0
  result_dart: ^1.1.1

  #ui
  oktoast: ^3.3.1
  flutter_snake_navigationbar: ^0.6.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0
  flutter_easyloading: ^3.0.5
  sizer: ^3.0.5
  flutter_screenutil: ^5.9.0
  asuka: ^2.2.1
  gap: ^3.0.1

  #navigation
  auto_route: ^8.0.3

  #images
  image_picker: ^1.0.0

  #dependency injection
  get_it: ^7.6.8
  injectable: ^2.4.1

  #access environment variables in .env file
  flutter_dotenv: ^5.1.0

  #generation models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  #restful API
  dio: ^5.4.2
  retrofit: ^4.1.0
  supabase_flutter: ^2.10.3
  equatable: ^2.0.7

  # auth
  font_awesome_flutter: ^10.8.0
  modal_bottom_sheet: ^3.0.0

  #socket
  web_socket_channel: ^3.0.1
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^19.5.0
  # reset password
  # app_links: ^6.4.1

  flutter_gen: 5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.4
  build_runner: ^2.4.9
  freezed: 2.5.2
  json_serializable: ^6.7.1
  auto_route_generator: ^8.0.0
  flutter_gen_runner: 5.4.0
  intl_utils: ^2.8.7
  injectable_generator: ^2.6.1
  retrofit_generator: ^8.1.0

# dependency_overrides:
#   share_plus: ^6.3.0  # Dùng version cũ ổn định hơn

flutter:
  uses-material-design: true
  assets:
    - assets/auth_images/
    - env/.env.dev
  fonts:
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Asimovian
      fonts:
        - asset: assets/fonts/Asimovian-Regular.ttf

flutter_gen:
  output: lib/generated/
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false
      style: dot-delimiter
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
